// <auto-generated />
namespace IranAudioGuide_MainServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Place_isPrimary_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Place_isPrimary_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201611071324003_Place_isPrimary_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
