// <auto-generated />
namespace IranAudioGuide_MainServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTimeSetUuidforuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTimeSetUuidforuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201701291242162_add-TimeSetUuid-for-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
