//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranAudioGuide_MainServer.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IranAudioGuide_MainServer.App_GlobalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alireza Motaghi.
        /// </summary>
        public static string aliReza {
            get {
                return ResourceManager.GetString("aliReza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Editor.
        /// </summary>
        public static string aliRezaOc {
            get {
                return ResourceManager.GetString("aliRezaOc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download it on App Store.
        /// </summary>
        public static string alt {
            get {
                return ResourceManager.GetString("alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get it on Google Play.
        /// </summary>
        public static string alt1 {
            get {
                return ResourceManager.GetString("alt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accurate information about Iran.
        /// </summary>
        public static string alt2 {
            get {
                return ResourceManager.GetString("alt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to listen to.
        /// </summary>
        public static string alt3 {
            get {
                return ResourceManager.GetString("alt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visit attractions with your own pace.
        /// </summary>
        public static string alt4 {
            get {
                return ResourceManager.GetString("alt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        public static string btnBuy {
            get {
                return ResourceManager.GetString("btnBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string btnPurchase {
            get {
                return ResourceManager.GetString("btnPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased.
        /// </summary>
        public static string btnPurchased {
            get {
                return ResourceManager.GetString("btnPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your payment gateway.
        /// </summary>
        public static string ChooseYourPaymentGateway {
            get {
                return ResourceManager.GetString("ChooseYourPaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp;amp; Conditions.
        /// </summary>
        public static string copyright2 {
            get {
                return ResourceManager.GetString("copyright2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy &amp;amp; Policy.
        /// </summary>
        public static string copyright21 {
            get {
                return ResourceManager.GetString("copyright21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiraz Dourandish Developers.
        /// </summary>
        public static string copyright22 {
            get {
                return ResourceManager.GetString("copyright22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer:.
        /// </summary>
        public static string copyright23 {
            get {
                return ResourceManager.GetString("copyright23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danial Babadi Yousefi.
        /// </summary>
        public static string danial {
            get {
                return ResourceManager.GetString("danial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string danialOc {
            get {
                return ResourceManager.GetString("danialOc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string DispalyCode {
            get {
                return ResourceManager.GetString("DispalyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ErrorComparePassword {
            get {
                return ResourceManager.GetString("ErrorComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed yet!.
        /// </summary>
        public static string ErrorEmailNotConfirmed {
            get {
                return ResourceManager.GetString("ErrorEmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For purchasing, first need to confirm your email. Please click &lt;a id=&apos;loginlink&apos; href=&apos;/en/Account/Login&apos;&gt;here&lt;/a&gt; to Login.
        /// </summary>
        public static string ErrorEmailNotConfirmedMessage {
            get {
                return ResourceManager.GetString("ErrorEmailNotConfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized device!.
        /// </summary>
        public static string ErrorPaymentUnauthorizedDevice {
            get {
                return ResourceManager.GetString("ErrorPaymentUnauthorizedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email  is already taken..
        /// </summary>
        public static string ErrorRegisterDuplicateUserName {
            get {
                return ResourceManager.GetString("ErrorRegisterDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  field is required..
        /// </summary>
        public static string ErrorRequire {
            get {
                return ResourceManager.GetString("ErrorRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  Email field is required..
        /// </summary>
        public static string ErrorRequiredEmail {
            get {
                return ResourceManager.GetString("ErrorRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string ErrorRequiredPassword {
            get {
                return ResourceManager.GetString("ErrorRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string ErrorRequiredRegisterName {
            get {
                return ResourceManager.GetString("ErrorRequiredRegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ErrorStringLengthMessage {
            get {
                return ResourceManager.GetString("ErrorStringLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error Please Try Again Later.
        /// </summary>
        public static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address to receive a reset password link.
        /// </summary>
        public static string forgotEnterEmail {
            get {
                return ResourceManager.GetString("forgotEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://iranaudioguide.net/Images.
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string IndexBtnLearnMore {
            get {
                return ResourceManager.GetString("IndexBtnLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only guide you will need in Iran.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only guide you will need in Iran.
        /// </summary>
        public static string IndexTitle01 {
            get {
                return ResourceManager.GetString("IndexTitle01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenient, thorough, liberating.
        /// </summary>
        public static string IndexTitle02 {
            get {
                return ResourceManager.GetString("IndexTitle02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran Audio Guide.
        /// </summary>
        public static string IranAudioGuide {
            get {
                return ResourceManager.GetString("IranAudioGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran Audio Guide Office.
        /// </summary>
        public static string IranAudioGuideOffice {
            get {
                return ResourceManager.GetString("IranAudioGuideOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        public static string LabelForRememberMe {
            get {
                return ResourceManager.GetString("LabelForRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa.
        /// </summary>
        public static string LangOther {
            get {
                return ResourceManager.GetString("LangOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LangTitle {
            get {
                return ResourceManager.GetString("LangTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string loadingtxt {
            get {
                return ResourceManager.GetString("loadingtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string MenuContactUs {
            get {
                return ResourceManager.GetString("MenuContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MenuProfile {
            get {
                return ResourceManager.GetString("MenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string MenuRegister {
            get {
                return ResourceManager.GetString("MenuRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mona Akhlaghi.
        /// </summary>
        public static string Mona {
            get {
                return ResourceManager.GetString("Mona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fars Science and Technology Park, Aryan town, Dr Hesabi Boulevard&lt;br/&gt;Shiraz, Iran.
        /// </summary>
        public static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - 404.
        /// </summary>
        public static string PageError0 {
            get {
                return ResourceManager.GetString("PageError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, The Page you entered not found!.
        /// </summary>
        public static string PageError1 {
            get {
                return ResourceManager.GetString("PageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what are you doing here?.
        /// </summary>
        public static string PageError2 {
            get {
                return ResourceManager.GetString("PageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to Iran Audio Guide home page.
        /// </summary>
        public static string PageError3 {
            get {
                return ResourceManager.GetString("PageError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PageProfile {
            get {
                return ResourceManager.GetString("PageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string PageProfile1 {
            get {
                return ResourceManager.GetString("PageProfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased.
        /// </summary>
        public static string PageProfile10 {
            get {
                return ResourceManager.GetString("PageProfile10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string PageProfile11 {
            get {
                return ResourceManager.GetString("PageProfile11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string PageProfile12 {
            get {
                return ResourceManager.GetString("PageProfile12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By pressing the.
        /// </summary>
        public static string PageProfile13 {
            get {
                return ResourceManager.GetString("PageProfile13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEACTIVATE OLD DEVICE.
        /// </summary>
        public static string PageProfile14 {
            get {
                return ResourceManager.GetString("PageProfile14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button you can deactivate your old device (your smart phone or tablet)..
        /// </summary>
        public static string PageProfile15 {
            get {
                return ResourceManager.GetString("PageProfile15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then sign in with the device you intend to use to set the device and gain access to your packages..
        /// </summary>
        public static string PageProfile16 {
            get {
                return ResourceManager.GetString("PageProfile16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remmember!.
        /// </summary>
        public static string PageProfile17 {
            get {
                return ResourceManager.GetString("PageProfile17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is only possible every 6 months once..
        /// </summary>
        public static string PageProfile18 {
            get {
                return ResourceManager.GetString("PageProfile18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Old Device.
        /// </summary>
        public static string PageProfile19 {
            get {
                return ResourceManager.GetString("PageProfile19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not set any devices to your account yet..
        /// </summary>
        public static string PageProfile2 {
            get {
                return ResourceManager.GetString("PageProfile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Confirmed yet!.
        /// </summary>
        public static string PageProfile20 {
            get {
                return ResourceManager.GetString("PageProfile20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your Email..
        /// </summary>
        public static string PageProfile21 {
            get {
                return ResourceManager.GetString("PageProfile21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you have not received the confirmation email yet, click.
        /// </summary>
        public static string PageProfile22 {
            get {
                return ResourceManager.GetString("PageProfile22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with international cards.
        /// </summary>
        public static string PageProfile23 {
            get {
                return ResourceManager.GetString("PageProfile23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with Iranian bank cards.
        /// </summary>
        public static string PageProfile24 {
            get {
                return ResourceManager.GetString("PageProfile24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Purchesed Pakages.
        /// </summary>
        public static string PageProfile25 {
            get {
                return ResourceManager.GetString("PageProfile25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to send you another Email.
        /// </summary>
        public static string PageProfile26 {
            get {
                return ResourceManager.GetString("PageProfile26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string PageProfile27 {
            get {
                return ResourceManager.GetString("PageProfile27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberating you to visit attractions with your own pace.
        /// </summary>
        public static string Parameter01 {
            get {
                return ResourceManager.GetString("Parameter01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No worries about being late or missing the explanations,take your time and wonder, take photos, ....
        /// </summary>
        public static string Parameter02 {
            get {
                return ResourceManager.GetString("Parameter02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where ever, when ever, which ever, how ever.
        /// </summary>
        public static string Parameter10 {
            get {
                return ResourceManager.GetString("Parameter10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While walking, sitting, photographing. In the hotel, on the way, in the plane, on the bus. In the morning, at night, in any hour you choose this guide will narrate what ever you feel like listening too.Pause the tracks, listen later. Just be sure to truly discover Iran with Iran audio guide..
        /// </summary>
        public static string Parameter11 {
            get {
                return ResourceManager.GetString("Parameter11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visiting tips.
        /// </summary>
        public static string Parameter12 {
            get {
                return ResourceManager.GetString("Parameter12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide will provide you with tips for visiting every attraction, maps and all you need to know about modern Iran.
        /// </summary>
        public static string Parameter13 {
            get {
                return ResourceManager.GetString("Parameter13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attraction guide.
        /// </summary>
        public static string Parameter14 {
            get {
                return ResourceManager.GetString("Parameter14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide will guide you step by step in every attraction. Advising you at what to look at and details not to miss.
        /// </summary>
        public static string Parameter15 {
            get {
                return ResourceManager.GetString("Parameter15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Parameter16 {
            get {
                return ResourceManager.GetString("Parameter16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide tell you Iran’s millenniums of history, historic stories, wars, victories and envasions.
        /// </summary>
        public static string Parameter17 {
            get {
                return ResourceManager.GetString("Parameter17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant figures.
        /// </summary>
        public static string Parameter18 {
            get {
                return ResourceManager.GetString("Parameter18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide will open up the story and achievements of Kings, poets, scientist and other significant people for you.
        /// </summary>
        public static string Parameter19 {
            get {
                return ResourceManager.GetString("Parameter19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian stories.
        /// </summary>
        public static string Parameter2 {
            get {
                return ResourceManager.GetString("Parameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide allows you to listen to famous persian myth tails, the great love stories, even the historic gossips, scandals of Persia.
        /// </summary>
        public static string Parameter20 {
            get {
                return ResourceManager.GetString("Parameter20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art &amp;amp; Architecture.
        /// </summary>
        public static string Parameter21 {
            get {
                return ResourceManager.GetString("Parameter21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide will explain the unique techniques and methods of Iranian architecture and crafts with images.
        /// </summary>
        public static string Parameter22 {
            get {
                return ResourceManager.GetString("Parameter22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who we are?.
        /// </summary>
        public static string Parameter23 {
            get {
                return ResourceManager.GetString("Parameter23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Iran Audio Guide appication has been created by a dedicated team with a combination of experties. We always feel obligied to present the highest standard in all aspects of our work.
        /// </summary>
        public static string Parameter24 {
            get {
                return ResourceManager.GetString("Parameter24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mona Akhlaghi.
        /// </summary>
        public static string Parameter25 {
            get {
                return ResourceManager.GetString("Parameter25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        public static string Parameter26 {
            get {
                return ResourceManager.GetString("Parameter26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soroosh Ansari Mehr.
        /// </summary>
        public static string Parameter27 {
            get {
                return ResourceManager.GetString("Parameter27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTO.
        /// </summary>
        public static string Parameter28 {
            get {
                return ResourceManager.GetString("Parameter28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to Contact us....
        /// </summary>
        public static string Parameter29 {
            get {
                return ResourceManager.GetString("Parameter29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string Parameter3 {
            get {
                return ResourceManager.GetString("Parameter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        public static string Parameter30 {
            get {
                return ResourceManager.GetString("Parameter30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name for this site below and click the Register button to finish
        ///        logging in..
        /// </summary>
        public static string Parameter31 {
            get {
                return ResourceManager.GetString("Parameter31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with:.
        /// </summary>
        public static string Parameter32 {
            get {
                return ResourceManager.GetString("Parameter32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured..
        /// </summary>
        public static string Parameter33 {
            get {
                return ResourceManager.GetString("Parameter33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with.
        /// </summary>
        public static string Parameter34 {
            get {
                return ResourceManager.GetString("Parameter34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your.
        /// </summary>
        public static string Parameter35 {
            get {
                return ResourceManager.GetString("Parameter35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Parameter36 {
            get {
                return ResourceManager.GetString("Parameter36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please{0}.
        /// </summary>
        public static string Parameter37 {
            get {
                return ResourceManager.GetString("Parameter37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string Parameter38 {
            get {
                return ResourceManager.GetString("Parameter38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string Parameter39 {
            get {
                return ResourceManager.GetString("Parameter39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string Parameter4 {
            get {
                return ResourceManager.GetString("Parameter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Link.
        /// </summary>
        public static string Parameter40 {
            get {
                return ResourceManager.GetString("Parameter40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string Parameter41 {
            get {
                return ResourceManager.GetString("Parameter41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome back!.
        /// </summary>
        public static string Parameter42 {
            get {
                return ResourceManager.GetString("Parameter42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us!.
        /// </summary>
        public static string Parameter43 {
            get {
                return ResourceManager.GetString("Parameter43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It only takes a minute!.
        /// </summary>
        public static string Parameter44 {
            get {
                return ResourceManager.GetString("Parameter44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By registering, you will access to all Iran Audio Guide has to offer.
        /// </summary>
        public static string Parameter45 {
            get {
                return ResourceManager.GetString("Parameter45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Parameter46 {
            get {
                return ResourceManager.GetString("Parameter46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Parameter47 {
            get {
                return ResourceManager.GetString("Parameter47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string Parameter48 {
            get {
                return ResourceManager.GetString("Parameter48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        public static string Parameter49 {
            get {
                return ResourceManager.GetString("Parameter49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider:.
        /// </summary>
        public static string Parameter5 {
            get {
                return ResourceManager.GetString("Parameter5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out..
        /// </summary>
        public static string Parameter50 {
            get {
                return ResourceManager.GetString("Parameter50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string Parameter51 {
            get {
                return ResourceManager.GetString("Parameter51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string PaymentPage2 {
            get {
                return ResourceManager.GetString("PaymentPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities Included.
        /// </summary>
        public static string PaymentPage21 {
            get {
                return ResourceManager.GetString("PaymentPage21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Gateway.
        /// </summary>
        public static string PaymentPage22 {
            get {
                return ResourceManager.GetString("PaymentPage22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check your payment trustfulness by click on ZarinPal Logo above.
        /// </summary>
        public static string PaymentPage23 {
            get {
                return ResourceManager.GetString("PaymentPage23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WebMoney.
        /// </summary>
        public static string PaymentPage24 {
            get {
                return ResourceManager.GetString("PaymentPage24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price :.
        /// </summary>
        public static string PaymentPage25 {
            get {
                return ResourceManager.GetString("PaymentPage25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string PaymentPage26 {
            get {
                return ResourceManager.GetString("PaymentPage26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Name.
        /// </summary>
        public static string PaymentPage27 {
            get {
                return ResourceManager.GetString("PaymentPage27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference ID.
        /// </summary>
        public static string PaymentPage28 {
            get {
                return ResourceManager.GetString("PaymentPage28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Info.
        /// </summary>
        public static string PaymentPage30 {
            get {
                return ResourceManager.GetString("PaymentPage30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By purchasing this package, you will again access to all audio guide  tracks in the cities mentioned above.
        ///Your purchased packages will be set on and accessible through your current user account..
        /// </summary>
        public static string PaymentPage31 {
            get {
                return ResourceManager.GetString("PaymentPage31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment procedure.
        /// </summary>
        public static string PaymentProcedure {
            get {
                return ResourceManager.GetString("PaymentProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to purchase a package, you either need an Iranian cash card or you have to use the webmoney transfer system which provides various payment methods..
        /// </summary>
        public static string PaymentProcedure1 {
            get {
                return ResourceManager.GetString("PaymentProcedure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure will only take a few minutes. The system will guide you through the steps. As soon the process has finished, the packages will be activated for you automatically. In case the procedures fail contact us..
        /// </summary>
        public static string PaymentProcedure2 {
            get {
                return ResourceManager.GetString("PaymentProcedure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string PaymentTermsConditions {
            get {
                return ResourceManager.GetString("PaymentTermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have purchased a packaged the price is not refundable.
        ///                        &lt;br /&gt;
        ///                        Iranaudioguide is not responsible for failure of the transaction. Contact your bank to follow up on failed transactions.
        ///                        &lt;br /&gt;
        ///                        Users agree to the price of each package and by purchasing a package, users terminate their right of any future complaint toward the price and content of the packages.
        ///                        &lt;br /&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentTermsConditions1 {
            get {
                return ResourceManager.GetString("PaymentTermsConditions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string PlaceholderConfirmPassword {
            get {
                return ResourceManager.GetString("PlaceholderConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message....
        /// </summary>
        public static string PlaceholderMessage {
            get {
                return ResourceManager.GetString("PlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City or Location.
        /// </summary>
        public static string PlaceholderSearchPackage {
            get {
                return ResourceManager.GetString("PlaceholderSearchPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string PlaceholderSubject {
            get {
                return ResourceManager.GetString("PlaceholderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        public static string PleaseTryAgain {
            get {
                return ResourceManager.GetString("PleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiebe Pourmand.
        /// </summary>
        public static string purmand {
            get {
                return ResourceManager.GetString("purmand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string purmandOc {
            get {
                return ResourceManager.GetString("purmandOc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user?.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser?.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference ID.
        /// </summary>
        public static string ReturnPaymentReferenceID {
            get {
                return ResourceManager.GetString("ReturnPaymentReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t just walk through  Iran, learn the history, hear the stories, feel the culture, ....
        /// </summary>
        public static string SectionOneH2 {
            get {
                return ResourceManager.GetString("SectionOneH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s so close to release.&lt;br /&gt;
        ///            We will notify you when we release..
        /// </summary>
        public static string SectionOneMessage {
            get {
                return ResourceManager.GetString("SectionOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Iran Audio Guide application for free and see for yourself&lt;br /&gt;.
        /// </summary>
        public static string SectionOneP {
            get {
                return ResourceManager.GetString("SectionOneP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing you with accurate information.
        /// </summary>
        public static string SectionTwoContentH2 {
            get {
                return ResourceManager.GetString("SectionTwoContentH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To guide you through the discovery of Iran and all its millenniums of history.
        /// </summary>
        public static string SectionTwoContentP {
            get {
                return ResourceManager.GetString("SectionTwoContentP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover iran while listening to facts and stories about modern Iran, ancient history, the arts, persian mythology and above all a step by step guide through notable attractions..
        /// </summary>
        public static string SEOdesc {
            get {
                return ResourceManager.GetString("SEOdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by clicking &lt;a href=&apos;{0} &apos;&gt;here&lt;/a&gt;.
        /// </summary>
        public static string ServerConfirmMessage {
            get {
                return ResourceManager.GetString("ServerConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        public static string ServerConfirmTitel {
            get {
                return ResourceManager.GetString("ServerConfirmTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check input fields.
        /// </summary>
        public static string ServerContactEmail {
            get {
                return ResourceManager.GetString("ServerContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have successfully deactivated your device. the next device you sign in with, will become your active device..
        /// </summary>
        public static string ServerDeactivateMobile {
            get {
                return ResourceManager.GetString("ServerDeactivateMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should expect to wait up to {0} days.
        /// </summary>
        public static string ServerDeactivateMobileInavlid {
            get {
                return ResourceManager.GetString("ServerDeactivateMobileInavlid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation.
        /// </summary>
        public static string ServerEmailConfirmation {
            get {
                return ResourceManager.GetString("ServerEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check your email.
        /// </summary>
        public static string ServerEmailConfirmationMessage {
            get {
                return ResourceManager.GetString("ServerEmailConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to send another confirmation email through your profile page. Please click &lt;a id=&apos;loginlink&apos; href=&apos;/en/Account/Login&apos;&gt;here&lt;/a&gt; to Login.
        /// </summary>
        public static string ServerEmailConfirmationMessage2 {
            get {
                return ResourceManager.GetString("ServerEmailConfirmationMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please click &lt;a id=&apos;loginlink&apos; href=&apos;/en/Account/Login&apos;&gt;here&lt;/a&gt; to Login.
        /// </summary>
        public static string ServerEmailConfirmationSucceeded {
            get {
                return ResourceManager.GetString("ServerEmailConfirmationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sending failed.
        /// </summary>
        public static string ServerEmailErrorSending {
            get {
                return ResourceManager.GetString("ServerEmailErrorSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! Your message sent successfully!..
        /// </summary>
        public static string ServerEmailSending {
            get {
                return ResourceManager.GetString("ServerEmailSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks!  sent successfully!. Please Check your email.
        /// </summary>
        public static string ServerEmailSendingSuccess {
            get {
                return ResourceManager.GetString("ServerEmailSendingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Failed!.
        /// </summary>
        public static string ServerErrorConfirmSubject {
            get {
                return ResourceManager.GetString("ServerErrorConfirmSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string ServerErrorInvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("ServerErrorInvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string ServerErrorUnknown {
            get {
                return ResourceManager.GetString("ServerErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ServerForgotPassword {
            get {
                return ResourceManager.GetString("ServerForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password. Please click &lt;a id=&apos;loginlink&apos; href=&apos;/en/Account/Login&apos;&gt;here&lt;/a&gt; to Login.
        /// </summary>
        public static string ServerForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ServerForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        public static string ServerInvalidCode {
            get {
                return ResourceManager.GetString("ServerInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string ServerInvalidLoginAttempt {
            get {
                return ResourceManager.GetString("ServerInvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout.
        /// </summary>
        public static string ServerLockout {
            get {
                return ResourceManager.GetString("ServerLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string ServerPasswordChanged {
            get {
                return ResourceManager.GetString("ServerPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed. Please click &lt;a id=&apos;loginlink&apos; href=&apos;/en/Account/Login&apos;&gt;here&lt;/a&gt; to Login.
        /// </summary>
        public static string ServerPasswordChangedMessage {
            get {
                return ResourceManager.GetString("ServerPasswordChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ServerResetPassword {
            get {
                return ResourceManager.GetString("ServerResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking &lt;a href=&apos;{0}&apos;&gt;here&lt;/a&gt;.
        /// </summary>
        public static string ServerResetPasswordMessage {
            get {
                return ResourceManager.GetString("ServerResetPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent a reset password link to &lt;strong style=&apos;color:red;&apos;&gt;{1}&lt;/strong&gt; &lt;br /&gt; didn&apos;t receive email? &lt;a href={0}&gt;Resend&lt;/a&gt;.
        /// </summary>
        public static string ServerResetPasswordMessage2 {
            get {
                return ResourceManager.GetString("ServerResetPasswordMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your Iran Audio Guide account easily through our website.
        /// </summary>
        public static string signInSubHeader {
            get {
                return ResourceManager.GetString("signInSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soroosh Ansari Mehr.
        /// </summary>
        public static string Soroosh {
            get {
                return ResourceManager.GetString("Soroosh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to listen to.
        /// </summary>
        public static string SpotlightContentH2 {
            get {
                return ResourceManager.GetString("SpotlightContentH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the tracks your interested in, choose among all the content available.
        /// </summary>
        public static string SpotlightContentP {
            get {
                return ResourceManager.GetString("SpotlightContentP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string TitlePageConfirmEmail {
            get {
                return ResourceManager.GetString("TitlePageConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string TitlePageForgot {
            get {
                return ResourceManager.GetString("TitlePageForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string TitlePageForgotConfirmation {
            get {
                return ResourceManager.GetString("TitlePageForgotConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string TitlePageLogIn {
            get {
                return ResourceManager.GetString("TitlePageLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string TitlePageLoginFailure {
            get {
                return ResourceManager.GetString("TitlePageLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string TitlePageRegister {
            get {
                return ResourceManager.GetString("TitlePageRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string TitlePageSendCode {
            get {
                return ResourceManager.GetString("TitlePageSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string TitlePayment {
            get {
                return ResourceManager.GetString("TitlePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Webmoney.
        /// </summary>
        public static string WebmoneyAbout {
            get {
                return ResourceManager.GetString("WebmoneyAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string WebmoneyAbout1 {
            get {
                return ResourceManager.GetString("WebmoneyAbout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebMoney ID.
        /// </summary>
        public static string WebmoneyAbout2 {
            get {
                return ResourceManager.GetString("WebmoneyAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 059551878952.
        /// </summary>
        public static string WebmoneyAbout3 {
            get {
                return ResourceManager.GetString("WebmoneyAbout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string WebmoneyAbout4 {
            get {
                return ResourceManager.GetString("WebmoneyAbout4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button &quot;Purchase&quot;, the page will go to the Webmoney transfer.&lt;br /&gt; You will see several methods of payment with web money. If you are a Webmoney user you can use the Webmoney keeper.&lt;br /&gt;If you’re not familiar with Webmoney services, choose the Quick payment. For the payment to proceed you will you need to receive a sms. So be sure your sim card is active and you can receive the text messages..
        /// </summary>
        public static string WebmoneyDescription {
            get {
                return ResourceManager.GetString("WebmoneyDescription", resourceCulture);
            }
        }
    }
}
