//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download it on App Store.
        /// </summary>
        internal static string alt {
            get {
                return ResourceManager.GetString("alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get it on Google Play.
        /// </summary>
        internal static string alt1 {
            get {
                return ResourceManager.GetString("alt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accurate information about Iran.
        /// </summary>
        internal static string alt2 {
            get {
                return ResourceManager.GetString("alt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to listen to.
        /// </summary>
        internal static string alt3 {
            get {
                return ResourceManager.GetString("alt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visit attractions with your own pace.
        /// </summary>
        internal static string alt4 {
            get {
                return ResourceManager.GetString("alt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        internal static string btnBuy {
            get {
                return ResourceManager.GetString("btnBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string btnPurchase {
            get {
                return ResourceManager.GetString("btnPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased.
        /// </summary>
        internal static string btnPurchased {
            get {
                return ResourceManager.GetString("btnPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp;amp; Conditions.
        /// </summary>
        internal static string copyright2 {
            get {
                return ResourceManager.GetString("copyright2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy &amp;amp; Policy.
        /// </summary>
        internal static string copyright21 {
            get {
                return ResourceManager.GetString("copyright21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soroosh Developer Team.
        /// </summary>
        internal static string copyright22 {
            get {
                return ResourceManager.GetString("copyright22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer:.
        /// </summary>
        internal static string copyright23 {
            get {
                return ResourceManager.GetString("copyright23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address to receive a reset password link.
        /// </summary>
        internal static string forgotEnterEmail {
            get {
                return ResourceManager.GetString("forgotEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string IndexBtnLearnMore {
            get {
                return ResourceManager.GetString("IndexBtnLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only guide you will need in Iran.
        /// </summary>
        internal static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only guide you will need in Iran.
        /// </summary>
        internal static string IndexTitle01 {
            get {
                return ResourceManager.GetString("IndexTitle01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenient, thorough, liberating.
        /// </summary>
        internal static string IndexTitle02 {
            get {
                return ResourceManager.GetString("IndexTitle02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        internal static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran Audio Guide.
        /// </summary>
        internal static string IranAudioGuide {
            get {
                return ResourceManager.GetString("IranAudioGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran Audio Guide Office.
        /// </summary>
        internal static string IranAudioGuideOffice {
            get {
                return ResourceManager.GetString("IranAudioGuideOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string MenuContactUs {
            get {
                return ResourceManager.GetString("MenuContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string MenuProfile {
            get {
                return ResourceManager.GetString("MenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string MenuRegister {
            get {
                return ResourceManager.GetString("MenuRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mona Akhlaghi.
        /// </summary>
        internal static string Mona {
            get {
                return ResourceManager.GetString("Mona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fars Science and Technology Park, Aryan town, Dr Hesabi Boulevard&lt;br/&gt;Shiraz, Iran.
        /// </summary>
        internal static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - 404.
        /// </summary>
        internal static string PageError0 {
            get {
                return ResourceManager.GetString("PageError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, The Page you entered not found!.
        /// </summary>
        internal static string PageError1 {
            get {
                return ResourceManager.GetString("PageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what are you doing here?.
        /// </summary>
        internal static string PageError2 {
            get {
                return ResourceManager.GetString("PageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to Iran Audio Guide home page.
        /// </summary>
        internal static string PageError3 {
            get {
                return ResourceManager.GetString("PageError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string PageProfile {
            get {
                return ResourceManager.GetString("PageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        internal static string PageProfile1 {
            get {
                return ResourceManager.GetString("PageProfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased.
        /// </summary>
        internal static string PageProfile10 {
            get {
                return ResourceManager.GetString("PageProfile10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string PageProfile11 {
            get {
                return ResourceManager.GetString("PageProfile11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string PageProfile12 {
            get {
                return ResourceManager.GetString("PageProfile12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By pressing the.
        /// </summary>
        internal static string PageProfile13 {
            get {
                return ResourceManager.GetString("PageProfile13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEACTIVATE OLD DEVICE.
        /// </summary>
        internal static string PageProfile14 {
            get {
                return ResourceManager.GetString("PageProfile14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button you can deactivate your old device (your smart phone or tablet)..
        /// </summary>
        internal static string PageProfile15 {
            get {
                return ResourceManager.GetString("PageProfile15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then sign in with the device you intend to use to set the device and gain access to your packages..
        /// </summary>
        internal static string PageProfile16 {
            get {
                return ResourceManager.GetString("PageProfile16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remmember!.
        /// </summary>
        internal static string PageProfile17 {
            get {
                return ResourceManager.GetString("PageProfile17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is only possible every 6 months once..
        /// </summary>
        internal static string PageProfile18 {
            get {
                return ResourceManager.GetString("PageProfile18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Old Device.
        /// </summary>
        internal static string PageProfile19 {
            get {
                return ResourceManager.GetString("PageProfile19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not set any devices to your account yet..
        /// </summary>
        internal static string PageProfile2 {
            get {
                return ResourceManager.GetString("PageProfile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Confirmed yet!.
        /// </summary>
        internal static string PageProfile20 {
            get {
                return ResourceManager.GetString("PageProfile20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your Email..
        /// </summary>
        internal static string PageProfile21 {
            get {
                return ResourceManager.GetString("PageProfile21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you have not received the confirmation email yet, click.
        /// </summary>
        internal static string PageProfile22 {
            get {
                return ResourceManager.GetString("PageProfile22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with international cards.
        /// </summary>
        internal static string PageProfile23 {
            get {
                return ResourceManager.GetString("PageProfile23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with Iranian bank cards.
        /// </summary>
        internal static string PageProfile24 {
            get {
                return ResourceManager.GetString("PageProfile24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Purchesed Pakages.
        /// </summary>
        internal static string PageProfile25 {
            get {
                return ResourceManager.GetString("PageProfile25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to send you another Email.
        /// </summary>
        internal static string PageProfile26 {
            get {
                return ResourceManager.GetString("PageProfile26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        internal static string PageProfile27 {
            get {
                return ResourceManager.GetString("PageProfile27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberating you to visit attractions with your own pace.
        /// </summary>
        internal static string Parameter01 {
            get {
                return ResourceManager.GetString("Parameter01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No worries about being late or missing the explanations,take your time and wonder, take photos, ....
        /// </summary>
        internal static string Parameter02 {
            get {
                return ResourceManager.GetString("Parameter02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where ever, when ever, which ever, how ever.
        /// </summary>
        internal static string Parameter10 {
            get {
                return ResourceManager.GetString("Parameter10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While walking, sitting, photographing. In the hotel, on the way, in the plane, on the bus. In the morning, at night, in any hour you choose this guide will narrate what ever you feel like listening too.Pause the tracks, listen later. Just be sure to truly discover Iran with Iran audio guide..
        /// </summary>
        internal static string Parameter11 {
            get {
                return ResourceManager.GetString("Parameter11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visiting tips.
        /// </summary>
        internal static string Parameter12 {
            get {
                return ResourceManager.GetString("Parameter12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide will provide you with tips for visiting every attraction, maps and all you need to know about modern Iran.
        /// </summary>
        internal static string Parameter13 {
            get {
                return ResourceManager.GetString("Parameter13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attraction guide.
        /// </summary>
        internal static string Parameter14 {
            get {
                return ResourceManager.GetString("Parameter14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide will guide you step by step in every attraction. Advising you at what to look at and details not to miss.
        /// </summary>
        internal static string Parameter15 {
            get {
                return ResourceManager.GetString("Parameter15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string Parameter16 {
            get {
                return ResourceManager.GetString("Parameter16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide tell you Iran’s millenniums of history, historic stories, wars, victories and envasions.
        /// </summary>
        internal static string Parameter17 {
            get {
                return ResourceManager.GetString("Parameter17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant figures.
        /// </summary>
        internal static string Parameter18 {
            get {
                return ResourceManager.GetString("Parameter18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide will open up the story and achievements of Kings, poets, scientist and other significant people for you.
        /// </summary>
        internal static string Parameter19 {
            get {
                return ResourceManager.GetString("Parameter19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian stories.
        /// </summary>
        internal static string Parameter2 {
            get {
                return ResourceManager.GetString("Parameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide allows you to listen to famous persian myth tails, the great love stories, even the historic gossips, scandals of Persia.
        /// </summary>
        internal static string Parameter20 {
            get {
                return ResourceManager.GetString("Parameter20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art &amp;amp; Architecture.
        /// </summary>
        internal static string Parameter21 {
            get {
                return ResourceManager.GetString("Parameter21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran audio guide will explain the unique techniques and methods of Iranian architecture and crafts with images.
        /// </summary>
        internal static string Parameter22 {
            get {
                return ResourceManager.GetString("Parameter22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who we are?.
        /// </summary>
        internal static string Parameter23 {
            get {
                return ResourceManager.GetString("Parameter23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Iran Audio Guide appication has been created by a dedicated team with a combination of experties. We always feel obligied to present the highest standard in all aspects of our work.
        /// </summary>
        internal static string Parameter24 {
            get {
                return ResourceManager.GetString("Parameter24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mona Akhlaghi.
        /// </summary>
        internal static string Parameter25 {
            get {
                return ResourceManager.GetString("Parameter25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        internal static string Parameter26 {
            get {
                return ResourceManager.GetString("Parameter26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soroosh Ansari Mehr.
        /// </summary>
        internal static string Parameter27 {
            get {
                return ResourceManager.GetString("Parameter27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTO.
        /// </summary>
        internal static string Parameter28 {
            get {
                return ResourceManager.GetString("Parameter28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to Contact us....
        /// </summary>
        internal static string Parameter29 {
            get {
                return ResourceManager.GetString("Parameter29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        internal static string Parameter3 {
            get {
                return ResourceManager.GetString("Parameter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        internal static string Parameter30 {
            get {
                return ResourceManager.GetString("Parameter30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name for this site below and click the Register button to finish
        ///        logging in..
        /// </summary>
        internal static string Parameter31 {
            get {
                return ResourceManager.GetString("Parameter31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with:.
        /// </summary>
        internal static string Parameter32 {
            get {
                return ResourceManager.GetString("Parameter32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured..
        /// </summary>
        internal static string Parameter33 {
            get {
                return ResourceManager.GetString("Parameter33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with.
        /// </summary>
        internal static string Parameter34 {
            get {
                return ResourceManager.GetString("Parameter34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your.
        /// </summary>
        internal static string Parameter35 {
            get {
                return ResourceManager.GetString("Parameter35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        internal static string Parameter36 {
            get {
                return ResourceManager.GetString("Parameter36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please{0}.
        /// </summary>
        internal static string Parameter37 {
            get {
                return ResourceManager.GetString("Parameter37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        internal static string Parameter38 {
            get {
                return ResourceManager.GetString("Parameter38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        internal static string Parameter39 {
            get {
                return ResourceManager.GetString("Parameter39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        internal static string Parameter4 {
            get {
                return ResourceManager.GetString("Parameter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Link.
        /// </summary>
        internal static string Parameter40 {
            get {
                return ResourceManager.GetString("Parameter40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        internal static string Parameter41 {
            get {
                return ResourceManager.GetString("Parameter41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome back!.
        /// </summary>
        internal static string Parameter42 {
            get {
                return ResourceManager.GetString("Parameter42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us!.
        /// </summary>
        internal static string Parameter43 {
            get {
                return ResourceManager.GetString("Parameter43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It only takes a minute!.
        /// </summary>
        internal static string Parameter44 {
            get {
                return ResourceManager.GetString("Parameter44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By registering, you will access to all Iran Audio Guide has to offer.
        /// </summary>
        internal static string Parameter45 {
            get {
                return ResourceManager.GetString("Parameter45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Parameter46 {
            get {
                return ResourceManager.GetString("Parameter46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string Parameter47 {
            get {
                return ResourceManager.GetString("Parameter47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        internal static string Parameter48 {
            get {
                return ResourceManager.GetString("Parameter48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        internal static string Parameter49 {
            get {
                return ResourceManager.GetString("Parameter49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider:.
        /// </summary>
        internal static string Parameter5 {
            get {
                return ResourceManager.GetString("Parameter5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out..
        /// </summary>
        internal static string Parameter50 {
            get {
                return ResourceManager.GetString("Parameter50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        internal static string Parameter51 {
            get {
                return ResourceManager.GetString("Parameter51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        internal static string PaymentPage2 {
            get {
                return ResourceManager.GetString("PaymentPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PaymentPage21 {
            get {
                return ResourceManager.GetString("PaymentPage21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Gateway.
        /// </summary>
        internal static string PaymentPage22 {
            get {
                return ResourceManager.GetString("PaymentPage22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check your payment trustfulness by click on ZarinPal Logo above.
        /// </summary>
        internal static string PaymentPage23 {
            get {
                return ResourceManager.GetString("PaymentPage23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WebMoney.
        /// </summary>
        internal static string PaymentPage24 {
            get {
                return ResourceManager.GetString("PaymentPage24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price :.
        /// </summary>
        internal static string PaymentPage25 {
            get {
                return ResourceManager.GetString("PaymentPage25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string PaymentPage26 {
            get {
                return ResourceManager.GetString("PaymentPage26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Name.
        /// </summary>
        internal static string PaymentPage27 {
            get {
                return ResourceManager.GetString("PaymentPage27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference ID.
        /// </summary>
        internal static string PaymentPage28 {
            get {
                return ResourceManager.GetString("PaymentPage28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string PlaceholderConfirmPassword {
            get {
                return ResourceManager.GetString("PlaceholderConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message....
        /// </summary>
        internal static string PlaceholderMessage {
            get {
                return ResourceManager.GetString("PlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string PlaceholderSubject {
            get {
                return ResourceManager.GetString("PlaceholderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user?.
        /// </summary>
        internal static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t just walk through  Iran, learn the history, hear the stories, feel the culture, ....
        /// </summary>
        internal static string SectionOneH2 {
            get {
                return ResourceManager.GetString("SectionOneH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s so close to release.&lt;br /&gt;
        ///            We will notify you when we release..
        /// </summary>
        internal static string SectionOneMessage {
            get {
                return ResourceManager.GetString("SectionOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Iran Audio Guide application for free and see for yourself&lt;br /&gt;.
        /// </summary>
        internal static string SectionOneP {
            get {
                return ResourceManager.GetString("SectionOneP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing you with accurate information.
        /// </summary>
        internal static string SectionTwoContentH2 {
            get {
                return ResourceManager.GetString("SectionTwoContentH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To guide you through the discovery of Iran and all its millenniums of history.
        /// </summary>
        internal static string SectionTwoContentP {
            get {
                return ResourceManager.GetString("SectionTwoContentP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover iran while listening to facts and stories about modern Iran, ancient history, the arts, persian mythology and above all a step by step guide through notable attractions..
        /// </summary>
        internal static string SEOdesc {
            get {
                return ResourceManager.GetString("SEOdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by clicking &lt;a href=&apos;{0} &apos;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string ServerConfirmMessage {
            get {
                return ResourceManager.GetString("ServerConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        internal static string ServerConfirmTitel {
            get {
                return ResourceManager.GetString("ServerConfirmTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check input fields.
        /// </summary>
        internal static string ServerContactEmail {
            get {
                return ResourceManager.GetString("ServerContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have successfully deactivated your device. the next device you sign in with, will become your active device..
        /// </summary>
        internal static string ServerDeactivateMobile {
            get {
                return ResourceManager.GetString("ServerDeactivateMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should expect to wait up to {0} days.
        /// </summary>
        internal static string ServerDeactivateMobileInavlid {
            get {
                return ResourceManager.GetString("ServerDeactivateMobileInavlid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation.
        /// </summary>
        internal static string ServerEmailConfirmation {
            get {
                return ResourceManager.GetString("ServerEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check your email.
        /// </summary>
        internal static string ServerEmailConfirmationMessage {
            get {
                return ResourceManager.GetString("ServerEmailConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to send another confirmation email through your profile page. Please click &lt;a id=&apos;loginlink&apos; href=&apos;/Account/Login&apos;&gt;here&lt;/a&gt; to Login.
        /// </summary>
        internal static string ServerEmailConfirmationMessage2 {
            get {
                return ResourceManager.GetString("ServerEmailConfirmationMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please click &lt;a id=&apos;loginlink&apos; href=&apos;/Account/Login&apos;&gt;here&lt;/a&gt; to Login.
        /// </summary>
        internal static string ServerEmailConfirmationSucceeded {
            get {
                return ResourceManager.GetString("ServerEmailConfirmationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sending failed.
        /// </summary>
        internal static string ServerEmailErrorSending {
            get {
                return ResourceManager.GetString("ServerEmailErrorSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! Your message sent successfully!..
        /// </summary>
        internal static string ServerEmailSending {
            get {
                return ResourceManager.GetString("ServerEmailSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks!  sent successfully!. Please Check your email.
        /// </summary>
        internal static string ServerEmailSendingSuccess {
            get {
                return ResourceManager.GetString("ServerEmailSendingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Failed!.
        /// </summary>
        internal static string ServerErrorConfirmSubject {
            get {
                return ResourceManager.GetString("ServerErrorConfirmSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string ServerErrorInvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("ServerErrorInvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string ServerErrorUnknown {
            get {
                return ResourceManager.GetString("ServerErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ServerForgotPassword {
            get {
                return ResourceManager.GetString("ServerForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password. Please click &lt;a id=&apos;loginlink&apos; href=&apos;/Account/Login&apos;&gt;here&lt;/a&gt; to Login.
        /// </summary>
        internal static string ServerForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ServerForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        internal static string ServerInvalidCode {
            get {
                return ResourceManager.GetString("ServerInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        internal static string ServerInvalidLoginAttempt {
            get {
                return ResourceManager.GetString("ServerInvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout.
        /// </summary>
        internal static string ServerLockout {
            get {
                return ResourceManager.GetString("ServerLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        internal static string ServerPasswordChanged {
            get {
                return ResourceManager.GetString("ServerPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed. Please click &lt;a id=&apos;loginlink&apos; href=&apos;/Account/Login&apos;&gt;here&lt;/a&gt; to Login.
        /// </summary>
        internal static string ServerPasswordChangedMessage {
            get {
                return ResourceManager.GetString("ServerPasswordChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ServerResetPassword {
            get {
                return ResourceManager.GetString("ServerResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking &lt;a href=&apos;{0}&apos;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string ServerResetPasswordMessage {
            get {
                return ResourceManager.GetString("ServerResetPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent a reset password link to &lt;strong style=&apos;color:red;&apos;&gt;{1}&lt;/strong&gt; &lt;br /&gt; didn&apos;t receive email? &lt;a href={0}&gt;Resend&lt;/a&gt;.
        /// </summary>
        internal static string ServerResetPasswordMessage2 {
            get {
                return ResourceManager.GetString("ServerResetPasswordMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your Iran Audio Guide account easily through our website.
        /// </summary>
        internal static string signInSubHeader {
            get {
                return ResourceManager.GetString("signInSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soroosh Ansari Mehr.
        /// </summary>
        internal static string Soroosh {
            get {
                return ResourceManager.GetString("Soroosh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to listen to.
        /// </summary>
        internal static string SpotlightContentH2 {
            get {
                return ResourceManager.GetString("SpotlightContentH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the tracks your interested in, choose among all the content available.
        /// </summary>
        internal static string SpotlightContentP {
            get {
                return ResourceManager.GetString("SpotlightContentP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        internal static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        internal static string TitlePageConfirmEmail {
            get {
                return ResourceManager.GetString("TitlePageConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string TitlePageForgot {
            get {
                return ResourceManager.GetString("TitlePageForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        internal static string TitlePageForgotConfirmation {
            get {
                return ResourceManager.GetString("TitlePageForgotConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string TitlePageLogIn {
            get {
                return ResourceManager.GetString("TitlePageLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        internal static string TitlePageLoginFailure {
            get {
                return ResourceManager.GetString("TitlePageLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string TitlePageRegister {
            get {
                return ResourceManager.GetString("TitlePageRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string TitlePageSendCode {
            get {
                return ResourceManager.GetString("TitlePageSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
    }
}
